version: 2.1
workflows:
  main:
    jobs:
      - release:
          context: brunoluiz
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/

jobs:
  release:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.06.0-ce
      - run: docker login --username $DOCKER_HUB_USER --password=$DOCKER_HUB_PASSWORD
      - run: curl -sL https://git.io/goreleaser | bash
